image: ubuntu:xenial

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_LFS_SKIP_SMUDGE: "1"

linux_cstrike_dedicated_x86:
  stage: build
  before_script:
  - dpkg --add-architecture i386
  - apt update && apt upgrade -y
  - apt install -y git curl wget ca-certificates libedit-dev libedit-dev:i386 zlib1g-dev zlib1g-dev:i386 python gcc gcc-multilib g++ g++-multilib pkg-config libopus-dev libopus-dev:i386
  script:
  - mkdir -p $CI_PROJECT_DIR/out
  - ./waf configure -T release -d --prefix=./out --build-game=cstrike
  - ./waf install -j$(nproc --all) 2>/dev/null
  artifacts:
    paths:
    - $CI_PROJECT_DIR/out

linux_hl2mp_dedicated_x86:
  stage: build
  before_script:
  - dpkg --add-architecture i386
  - apt update && apt upgrade -y
  - apt install -y git curl wget ca-certificates libedit-dev libedit-dev:i386 zlib1g-dev zlib1g-dev:i386 python gcc gcc-multilib g++ g++-multilib pkg-config libopus-dev libopus-dev:i386
  script:
  - mkdir -p $CI_PROJECT_DIR/out
  - ./waf configure -T release -d --prefix=./out --build-game=hl2mp
  - ./waf install -j$(nproc --all) 2>/dev/null
  artifacts:
    paths:
    - $CI_PROJECT_DIR/out

windows_cstrike_dedicated_x86:
  stage: build
  tags:
  - shared-windows
  - windows
  - windows-1809
  before_script:
  - Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.0/python-3.7.0.exe" -OutFile "c:/temp/python-3.7.0.exe"
  - c:/temp/python-3.7.0.exe /quiet InstallAllUsers=0 PrependPath=1 Include_test=0
  script:
  - mkdir ./out
  - ./waf configure -T release -d --prefix=./out --build-game=cstrike
  - ./waf install 2>/dev/null
  artifacts:
    paths:
    - ./out

windows_hl2mp_dedicated_x86:
  stage: build
  tags:
  - shared-windows
  - windows
  - windows-1809
  before_script:
  - Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.0/python-3.7.0.exe" -OutFile "c:/temp/python-3.7.0.exe"
  - c:/temp/python-3.7.0.exe /quiet InstallAllUsers=0 PrependPath=1 Include_test=0
  script:
  - mkdir ./out
  - ./waf configure -T release -d --prefix=./out --build-game=cstrike
  - ./waf install 2>/dev/null
  artifacts:
    paths:
    - ./out
